name: Bug Report
description: Report a bug encountered while operating Kubernetes
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: 7 high vulnerabilities flagged this csi sidecar image  "external-attacher:v4.3.0"
      description: |
          7 high severity CVEs, which are listed in the prisma cloud's container image scan report and they were just released along with CSI powerflex version 2.7.0. Are there any solutions for these vulnerabilities flagged against  "external-attacher:v4.3.0" sidecar image ?  If anyone encounters these vulnerabilities , Please provide advice on how to address these vulnerabilities
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Please provide advice on how to address these vulnerabilities flagged for external-attacher:v4.3.0 CVE-2023-29400 ,CVE-2023-29405,CVE-2023-24540,CVE-2023-29404,CVE-2023-24539,CVE-2023-29403,CVE-2023-29402
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: would like to know how to remediate these CVEs CVE-2023-29400 ,CVE-2023-29405,CVE-2023-24540,CVE-2023-29404,CVE-2023-24539,CVE-2023-29403,CVE-2023-29402
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: kubeVersion
    attributes:
      label: Kubernetes version
      value: |
        <details>

        ```console
        $ kubectl version
        WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
        Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:23Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
         Kustomize Version: v5.0.1
         Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.6-mirantis-1", GitCommit:"2fe0af94e03afce4b799db63fd34271f97e4f9e9", GitTreeState:"clean", BuildDate:"2022-09-22T00:34:29Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
         WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
         ```

      
    validations:
      required: true

  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud provider
      value: |
        its on perm K8 infra.
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: OS version
      value: |
        <details>

        ```console
        # On Linux:
        $ cat /etc/os-release
        # paste output here
        $ uname -a
        # paste output here

        # On Windows:
        C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
        # paste output here
        ```

        </details>

  - type: textarea
    id: installer
    attributes:
      label: Install tools
      value: |
        <details>

        </details>

  - type: textarea
    id: runtime
    attributes:
      label: Container runtime (CRI) and version (if applicable)
      value: |
        <details>

        </details>

  - type: textarea
    id: plugins
    attributes:
      label: Related plugins (CNI, CSI, ...) and versions (if applicable)
      value: |
        <details>

        </details>
